name: deep_art_example
description: Demonstrates how to use the deep_art plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  photo_view: ^0.5.0
  image_picker: any
  image: any
  camera: any
  sqflite: ^1.1.6+5
  path_provider: ^1.3.0
  esys_flutter_share: ^1.0.2
  image_gallery_saver: ^1.2.2
  share:
    git: https://github.com/mth2610/share.git
  artistic_style_transfer:
    git: https://github.com/mth2610/artistic_style_transfer.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  deep_art:
    path: ../

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/cuctinhy.jpg
    - assets/canh.jpg
    - assets/giay.jpg
    - assets/nguoi.jpg
    - assets/style0.jpg
    - assets/style1.jpg
    - assets/style2.jpg
    - assets/style3.jpg
    - assets/style4.jpg
    - assets/style5.jpg
    - assets/style6.jpg
    - assets/style7.jpg
    - assets/style8.jpg
    - assets/style9.jpg
    - assets/style10.jpg
    - assets/style11.jpg
    - assets/style12.jpg
    - assets/style13.jpg
    - assets/style14.jpg
    - assets/style15.jpg
    - assets/style16.jpg
    - assets/style17.jpg
    - assets/style18.jpg
    - assets/style19.jpg
    - assets/style20.jpg
    - assets/style21.jpg
    - assets/style22.jpg
    - assets/style23.jpg
    - assets/style24.jpg
    - assets/style25.jpg
    - assets/0.jpeg
    - assets/1.jpg
    - assets/2.jpg
    - assets/3.jpg
    - assets/4.jpg
    - assets/5.jpg
    - assets/6.jpg
    - assets/7.jpg
    - assets/8.jpg
    - assets/9.jpg
    - assets/10.jpg
    - assets/11.jpg